import keyMirror from 'keymirror';

export const ACTIONS = keyMirror({
  SIGN_MODAL_VISIBILITY: null,
  SIGN_SHOW_INFO_PLUGIN: null,

  SIGN_DOC_ADD                : null,
  SIGN_DOC_ADD_AND_TRY_SIGNING: null,
  SIGN_SAVE_TYPE_SIGN: null,

  SIGN_CRYPTO_PROFILES_LOAD_REQUEST: null,
  SIGN_CRYPTO_PROFILES_LOAD_SUCCESS: null,
  SIGN_CRYPTO_PROFILES_LOAD_FAIL   : null,

  SIGN_CREATE_REQUEST: null,
  SIGN_CREATE_SUCCESS: null,
  SIGN_CREATE_FAIL   : null,

  SIGN_PREPARE         : null,
  SIGN_DELETE          : null,
  SIGN_DOCUMENT_REQUEST: null,
  SIGN_DOCUMENT_SUCCESS: null,

  SIGN_SMS_DOCUMENT_REQUEST: null,
  SIGN_SMS_DOCUMENT_SUCCESS: null,
  SIGN_SMS_DOCUMENT_FAIL   : null,


  SIGN_SET_SMS_CODE   : null,
  SIGN_REGEN_SMS_CODE : null,
  SIGN_CLEAR_DATA     : null,

  SIGN_DOCUMENT_SEND_SUCCESS: null,

  SIGN_DOCUMENT_SEND_FAIL: null,

  SIGN_SAVE_SIGNED_DOCUMENTS: null,
  SIGN_SAVE_REALITY_SIGN_DOCUMENTS: null,

  SIGN_SAVE_CHANNEL: null,

  SIGN_SET_STATUS_PENDING: null,

  SIGN_CRYPTOPRO_GET_ULK_FOR_REGENERATE_SUCCESS: null,
  SIGN_CRYPTOPRO_GET_ULK_FOR_REGENERATE_FAIL: null,

  SIGN_CRYPTO_OPERATION_DELETE_SUCCESS: null,
  SIGN_CRYPTO_OPERATION_DELETE_FAIL: null,

  SIGN_CRYPTO_OPERATION_PRINT_SUCCESS: null,
  SIGN_CRYPTO_OPERATION_PRINT_FAIL: null,

  SIGN_CRYPTO_OPERATION_DOWNLOAD_ACTIVE_CERT_SUCCESS: null,
  SIGN_CRYPTO_OPERATION_DOWNLOAD_ACTIVE_CERT_FAIL: null
});
